wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.28.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702617587.017499
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 70
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 70
      3:
      - 23
      - 35
      4: 3.10.10
      5: 0.16.1
      6: 4.28.0.dev0
      8:
      - 5
      13: linux-x86_64
